import H3 from "@/components/common/H3";
import { DataTable } from "./TableData";
import { columns } from "./UserColumns";
import { User } from "@/utils/types";

const ManageUsers = () => {
  const data: User[] = [
    {
      id: "1",
      username: "john_doe",
      firstName: "John",
      lastName: "Doe",
      email: "john.doe@example.com",
      roles: ["USER"],
      avatar: "https://randomuser.me/api/portraits/men/1.jpg",
      noPassword: false,
    },
    {
      id: "2",
      username: "jane_doe",
      firstName: "Jane",
      lastName: "Doe",
      email: "jane.doe@example.com",
      roles: ["ADMIN"],
      avatar: "https://randomuser.me/api/portraits/women/2.jpg",
      noPassword: true,
    },
    {
      id: "3",
      username: "alice_smith",
      firstName: "Alice",
      lastName: "Smith",
      email: "alice.smith@example.com",
      roles: ["USER"],
      avatar: "https://randomuser.me/api/portraits/women/3.jpg",
      noPassword: false,
    },
    {
      id: "4",
      username: "bob_jones",
      firstName: "Bob",
      lastName: "Jones",
      email: "bob.jones@example.com",
      roles: ["USER"],
      avatar: "https://randomuser.me/api/portraits/men/4.jpg",
      noPassword: true,
    },
    {
      id: "5",
      username: "charlie_brown",
      firstName: "Charlie",
      lastName: "Brown",
      email: "charlie.brown@example.com",
      roles: ["USER"],
      avatar: "https://randomuser.me/api/portraits/men/5.jpg",
      noPassword: false,
    },
    {
      id: "6",
      username: "david_wilson",
      firstName: "David",
      lastName: "Wilson",
      email: "david.wilson@example.com",
      roles: ["ADMIN", "USER"],
      avatar: "https://randomuser.me/api/portraits/men/6.jpg",
      noPassword: false,
    },
    {
      id: "7",
      username: "emma_watson",
      firstName: "Emma",
      lastName: "Watson",
      email: "emma.watson@example.com",
      roles: ["USER"],
      avatar: "https://randomuser.me/api/portraits/women/7.jpg",
      noPassword: false,
    },
    {
      id: "8",
      username: "frank_white",
      firstName: "Frank",
      lastName: "White",
      email: "frank.white@example.com",
      roles: ["USER"],
      avatar: "https://randomuser.me/api/portraits/men/8.jpg",
      noPassword: true,
    },
    {
      id: "9",
      username: "grace_adams",
      firstName: "Grace",
      lastName: "Adams",
      email: "grace.adams@example.com",
      roles: ["ADMIN"],
      avatar: "https://randomuser.me/api/portraits/women/9.jpg",
      noPassword: false,
    },
    {
      id: "10",
      username: "henry_james",
      firstName: "Henry",
      lastName: "James",
      email: "henry.james@example.com",
      roles: ["USER"],
      avatar: "https://randomuser.me/api/portraits/men/10.jpg",
      noPassword: false,
    },
    {
      id: "11",
      username: "isabella_clark",
      firstName: "Isabella",
      lastName: "Clark",
      email: "isabella.clark@example.com",
      roles: ["USER"],
      avatar: "https://randomuser.me/api/portraits/women/11.jpg",
      noPassword: false,
    },
    {
      id: "12",
      username: "jack_martin",
      firstName: "Jack",
      lastName: "Martin",
      email: "jack.martin@example.com",
      roles: ["USER", "USER"],
      avatar: "https://randomuser.me/api/portraits/men/12.jpg",
      noPassword: true,
    },
    {
      id: "13",
      username: "karen_taylor",
      firstName: "Karen",
      lastName: "Taylor",
      email: "karen.taylor@example.com",
      roles: ["USER"],
      avatar: "https://randomuser.me/api/portraits/women/13.jpg",
      noPassword: false,
    },
    {
      id: "14",
      username: "lewis_king",
      firstName: "Lewis",
      lastName: "King",
      email: "lewis.king@example.com",
      roles: ["USER"],
      avatar: "https://randomuser.me/api/portraits/men/14.jpg",
      noPassword: true,
    },
    {
      id: "15",
      username: "mia_evans",
      firstName: "Mia",
      lastName: "Evans",
      email: "mia.evans@example.com",
      roles: ["USER"],
      avatar: "https://randomuser.me/api/portraits/women/15.jpg",
      noPassword: false,
    },
    {
      id: "16",
      username: "noah_baker",
      firstName: "Noah",
      lastName: "Baker",
      email: "noah.baker@example.com",
      roles: ["USER"],
      avatar: "https://randomuser.me/api/portraits/men/16.jpg",
      noPassword: false,
    },
    {
      id: "17",
      username: "olivia_hall",
      firstName: "Olivia",
      lastName: "Hall",
      email: "olivia.hall@example.com",
      roles: ["ADMIN"],
      avatar: "https://randomuser.me/api/portraits/women/17.jpg",
      noPassword: false,
    },
    {
      id: "18",
      username: "peter_wright",
      firstName: "Peter",
      lastName: "Wright",
      email: "peter.wright@example.com",
      roles: ["USER"],
      avatar: "https://randomuser.me/api/portraits/men/18.jpg",
      noPassword: true,
    },
    {
      id: "19",
      username: "quincy_wood",
      firstName: "Quincy",
      lastName: "Wood",
      email: "quincy.wood@example.com",
      roles: ["USER"],
      avatar: "https://randomuser.me/api/portraits/men/19.jpg",
      noPassword: false,
    },
    {
      id: "20",
      username: "rachel_lewis",
      firstName: "Rachel",
      lastName: "Lewis",
      email: "rachel.lewis@example.com",
      roles: ["ADMIN", "USER"],
      avatar: "https://randomuser.me/api/portraits/women/20.jpg",
      noPassword: false,
    },
  ];
  return (
    <div className="py-8">
      <H3>Quản lý người dùng</H3>
      <div className="mt-6">
        <DataTable columns={columns} data={data} />
      </div>
    </div>
  );
};

export default ManageUsers;
